// Wrapper around IndexedDB.

// In theory, I could have a table registry where we track all the
// initializations.  We could take a list of "upgrades" including
// the expected version number at each and what to do to update, and
// it's an error if we're missing one - this would still essentially
// require all downstream includes to be present: it's organizationally
// distributed, but not truly distributed in the sense of everything
// being loosely required.  But it's also a much bigger pain.

import { ActivityId, ActivityType, Branch } from './branch';
import type { Patrol } from './trailman';
import { assertType } from './util';

const DB_NAME = '__sdh__tlcHelper';
const DB_VERSION = 1;

const STORE_BRANCH_REQUIREMENTS = 'branchRequirements';
const STORE_ACTIVITY_SPECS = 'activitySpecs';
const STORE_TRAILMEN = 'trailmen';
const STORE_COMPLETED_ACTIVITIES = 'concreteActivities';
const STORE_SCHEDULED_ACTIVITIES = 'scheduledActivities';

interface BranchRequirements {
  branch: Branch;
  needCoreSteps: number;
  needElectives: number;
}

interface ActivitySpec {
  id: ActivityId;
  name: string;
  branch: Branch;
  type: ActivityType;
}

interface ScheduledActivity {
  id?: number; // autogenerated
  activity: ActivityId;
  date: string; // PlainDate
  event: string;
  excludedPatrols: Patrol[]; // Which patrols does this not count for?
}

interface CompletedActivity {
  id: string; // trailmanid:activityid
  trailman: string; // id
  activity: string; // id
  branch: string; // needed for indexing
  date: string; // PlainDate
  note: string;
}

const upgrades: Record<number, (db: IDBDatabase, txn: IDBTransaction) => void> = {
  1: (db: IDBDatabase, _txn: IDBTransaction) => {
    // Branch requirements
    // if (!db.objectStoreNames.contains(STORE_BRANCH_REQUIEMENTS)) { ... }
    db.createObjectStore(STORE_BRANCH_REQUIREMENTS, {keyPath: 'branch'});

    // Activity specs
    const activitySpecs = db.createObjectStore(STORE_ACTIVITY_SPECS, {keyPath: 'id'});
    activitySpecs.createIndex('branch', 'branch', {unique: false});

    // Trailmen
    const trailmen = db.createObjectStore(STORE_TRAILMEN, {keyPath: 'id'});
    trailmen.createIndex('name', 'name', {unique: true});
    trailmen.createIndex('patrol', 'patrol', {unique: false});
    trailmen.createIndex('year', 'year', {unique: false});
    trailmen.createIndex('subpatrol', 'subpatrol', {unique: false});

    // Concrete activities
    const completedActivities = db.createObjectStore(STORE_COMPLETED_ACTIVITIES, {keyPath: 'id'});
    completedActivities.createIndex('trailman', 'trailman', {unique: false});
    completedActivities.createIndex('trailman_branch', ['trailman', 'branch'], {unique: false});

    // Scheduled activities - no need for an index since there's just a handful
    db.createObjectStore(STORE_SCHEDULED_ACTIVITIES, {keyPath: 'id', autoIncrement: true});
  },
};

class Database {
  private storeName: string = "messages";
  private db: IDBDatabase | null = null;

  static async open(): Promise<Database> {
    const store = new Database();
    await store.initialize();
    return store;
  }

  private constructor() {}

  /** Initializes the database connection. */
  private async initialize(): Promise<void> {
    return new Promise((resolve, reject) => {
      const request = indexedDB.open(DB_NAME, DB_VERSION);

      request.onupgradeneeded = (event: IDBVersionChangeEvent) => {
        for (let i = event.oldVersion + 1; i <= DB_VERSION; i++) {
          assertType<IDBOpenDBRequest>(event.target);
          upgrades[i]!(event.target.result, event.target.transaction!);
        }
      };

      request.onsuccess = (event) => {
        this.db = (event.target as IDBOpenDBRequest).result;
        // TODO - do we need to migrate any data?
        resolve();
      };

      request.onerror = (event) => {
        reject(`Database error: ${(event.target as IDBOpenDBRequest).error}`);
      };
    });
  }

  // TODO - memoize synchronous data
  

  /** Inserts a new message record. */
  async insertMessage(recipient: string, subject: string, message: string): Promise<number> {
    const store = this.getStore("readwrite");
    const entry: IMessage = { recipient, subject, message };
    
    return new Promise((resolve, reject) => {
      const request = store.add(entry);
      request.onsuccess = () => resolve(request.result as number);
      request.onerror = () => reject("Failed to insert message");
    });
  }

  /** Retrieves all messages from the store. */
  async readAllMessages(): Promise<IMessage[]> {
    const store = this.getStore("readonly");
    
    return new Promise((resolve, reject) => {
      const request = store.getAll();
      request.onsuccess = () => resolve(request.result as IMessage[]);
      request.onerror = () => reject("Failed to read messages");
    });
  }

  /** Deletes a specific message by its ID. */
  async deleteMessage(id: number): Promise<void> {
    const store = this.getStore("readwrite");
    
    return new Promise((resolve, reject) => {
      const request = store.delete(id);
      request.onsuccess = () => resolve();
      request.onerror = () => reject(`Failed to delete message with ID: ${id}`);
    });
  }

  /** Deletes the entire database. */
  async deleteDatabase(): Promise<void> {
    if (this.db) {
      this.db.close();
      this.db = null;
    }

    return new Promise((resolve, reject) => {
      const request = indexedDB.deleteDatabase(this.dbName);
      request.onsuccess = () => resolve();
      request.onerror = () => reject("Failed to delete database");
      request.onblocked = () => console.warn("Delete blocked: close other tabs.");
    });
  }

  /** Private helper to access the object store. */
  private getStore(mode: IDBTransactionMode): IDBObjectStore {
    if (!this.db) {
      throw new Error("Database not initialized. Call initDB() first.");
    }
    const transaction = this.db.transaction(this.storeName, mode);
    return transaction.objectStore(this.storeName);
  }
}





// type IDbUpgrade = [
//   oldVersion: number,
//   upgrade?: (db: IDBDatabase) => Promise<void>,
// ];

// export class IDb<T> {
//   constructor(
//     private readonly storeName: string,
//     private readonly upgrades: IDbUpgrade[],
//   ) {
//     // TODO - register
//     [] = [this.storeName, this.upgrades, DB_NAME];
//   }

//   get(): T {
//     throw new Error();
//   }
// }

// export interface IMessage {
//   id?: number;
//   recipient: string;
//   subject: string;
//   message: string;
// }
