// Wrapper around IndexedDB.

// In theory, I could have a table registry where we track all the
// initializations.  We could take a list of "upgrades" including
// the expected version number at each and what to do to update, and
// it's an error if we're missing one - this would still essentially
// require all downstream includes to be present: it's organizationally
// distributed, but not truly distributed in the sense of everything
// being loosely required.  But it's also a much bigger pain.

// import { ActivityId, ActivityType, Branch } from './branch';
// import type { Patrol } from './trailman';
// import { assertType } from './util';

import { openDB, type DBSchema, type IDBPDatabase } from 'idb';

// const STORE_BRANCH_REQUIREMENTS = 'branchRequirements';
// const STORE_ACTIVITY_SPECS = 'activitySpecs';
// const STORE_TRAILMEN = 'trailmen';
// const STORE_COMPLETED_ACTIVITIES = 'concreteActivities';
// const STORE_SCHEDULED_ACTIVITIES = 'scheduledActivities';

interface TLCSchema extends DBSchema {
  'completed-activities': {
    key: string;
    value: { // CompletedActivity
      id: string; // trailmanid:activityid
      trailman: string; // id
      activity: string; // id
      branch: string; // needed for indexing
      date: string; // PlainDate
      note: string;
    };
    indexes: {
      'by-trailman-and-branch': [trailmanId: string, branchName: string];
      //'by-branch-and-trailman': [branchName: string, trailmanId: string];
    };
  };
}
export type CompletedActivity = TLCSchema['completed-activities']['value'];

// interface EarnedAwards {
//   trailman: string;
//   award: string; // branch pin, branch star, joining, forest, worthy life, timberline, ???
//   earnedDate: string; // PlainDate
//   awardedDate?: string; // PlainDate if awarded
// }

// interface BranchRequirements {
//   branch: Branch;
//   needCoreSteps: number;
//   needElectives: number;
// }

// interface ActivitySpec {
//   id: ActivityId;
//   name: string;
//   branch: Branch;
//   type: ActivityType;
// }

// interface ScheduledActivity {
//   id?: number; // autogenerated
//   activity: ActivityId;
//   date: string; // PlainDate
//   event: string;
//   excludedPatrols: Patrol[]; // Which patrols does this not count for?
// }

export class Database {
  private db!: IDBPDatabase<TLCSchema>;

  static async open(): Promise<Database> {
    const store = new Database();
    await store.initialize();
    return store;
  }

  private constructor() {}

  /** Initializes the database connection. */
  private async initialize(): Promise<void> {
    this.db = await openDB<TLCSchema>('__sdh__tlcHelper', /* version= */ 1, {
      upgrade(db, oldVersion, _newVersion, _transaction, _event) {
        if (oldVersion < 1) {
          // Concrete activities
          const completedActivities = db.createObjectStore('completed-activities', {keyPath: 'id'});
          completedActivities.createIndex('by-trailman-and-branch', ['trailman', 'branch'], {unique: false});
          //completedActivities.createIndex('by-branch-and-trailman', ['branch', 'trailman'], {unique: false});
        }

        // // Branch requirements
        // db.createObjectStore(STORE_BRANCH_REQUIREMENTS, {keyPath: 'branch'});

        // // Activity specs
        // {
        //   const activitySpecs = db.createObjectStore(STORE_ACTIVITY_SPECS, {keyPath: 'id'});
        //   activitySpecs.createIndex('branch', 'branch', {unique: false});
        // }

        // // Trailmen
        // {
        //   const trailmen = db.createObjectStore(STORE_TRAILMEN, {keyPath: 'id'});
        //   trailmen.createIndex('name', 'name', {unique: true});
        //   trailmen.createIndex('patrol', 'patrol', {unique: false});
        //   trailmen.createIndex('year', 'year', {unique: false});
        //   trailmen.createIndex('subpatrol', 'subpatrol', {unique: false});
        // }

        // // Scheduled activities - no need for an index since there's just a handful
        // db.createObjectStore(STORE_SCHEDULED_ACTIVITIES, {keyPath: 'id', autoIncrement: true});
      },
    });
  }

  async getCompletedActivitiesForTrailman(trailmanId: string): Promise<CompletedActivity[]> {
    return await this.db.getAllFromIndex(
      'completed-activities',
      'by-trailman-and-branch',
      IDBKeyRange.bound([trailmanId], [trailmanId, []]),
    );
  }

  async replaceCompletedActivities(branch: string, data: Map</* trailmanId */ string, CompletedActivity[]>): Promise<void> {
    const tx = this.db.transaction('completed-activities', 'readwrite');
    const store = tx.objectStore('completed-activities');
    const index = store.index('by-trailman-and-branch');
    for (const [trailman, activities] of Object.entries(data)) {
      let cursor = await index.openKeyCursor(IDBKeyRange.only([trailman, branch]));
      while (cursor) {
        await store.delete(cursor.primaryKey);
        cursor = await cursor.continue();
      }
      for (const activity of activities) {
        store.add(activity);
      }
    }
    await tx.done;
  }

  // TODO - memoize synchronous data??
  

  // /** Inserts a new message record. */
  // async insertMessage(recipient: string, subject: string, message: string): Promise<number> {
  //   const store = this.getStore("readwrite");
  //   const entry: IMessage = { recipient, subject, message };
    
  //   return new Promise((resolve, reject) => {
  //     const request = store.add(entry);
  //     request.onsuccess = () => resolve(request.result as number);
  //     request.onerror = () => reject("Failed to insert message");
  //   });
  // }

  // /** Retrieves all messages from the store. */
  // async readAllMessages(): Promise<IMessage[]> {
  //   const store = this.getStore("readonly");
    
  //   return new Promise((resolve, reject) => {
  //     const request = store.getAll();
  //     request.onsuccess = () => resolve(request.result as IMessage[]);
  //     request.onerror = () => reject("Failed to read messages");
  //   });
  // }

  // /** Deletes a specific message by its ID. */
  // async deleteMessage(id: number): Promise<void> {
  //   const store = this.getStore("readwrite");
    
  //   return new Promise((resolve, reject) => {
  //     const request = store.delete(id);
  //     request.onsuccess = () => resolve();
  //     request.onerror = () => reject(`Failed to delete message with ID: ${id}`);
  //   });
  // }

  // /** Deletes the entire database. */
  // async deleteDatabase(): Promise<void> {
  //   if (this.db) {
  //     this.db.close();
  //     this.db = null;
  //   }

  //   return new Promise((resolve, reject) => {
  //     const request = indexedDB.deleteDatabase(this.dbName);
  //     request.onsuccess = () => resolve();
  //     request.onerror = () => reject("Failed to delete database");
  //     request.onblocked = () => console.warn("Delete blocked: close other tabs.");
  //   });
  // }

  // /** Private helper to access the object store. */
  // private getStore(mode: IDBTransactionMode): IDBObjectStore {
  //   if (!this.db) {
  //     throw new Error("Database not initialized. Call initDB() first.");
  //   }
  //   const transaction = this.db.transaction(this.storeName, mode);
  //   return transaction.objectStore(this.storeName);
  // }
}
